services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-server
    restart: unless-stopped

    command:
      # uncomment if ansible download
      - "-m"
      - "/models/Spark-X2.5-4B-Q4_K_M.gguf"
      # - "-hf"
      # - "bartowski/Qwen_Qwen3-4B-Thinking-2507-GGUF:Q4_K_M"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      # 8k context
      # - "--ctx-size"
      # - "8192"
      # 32k context size
      - "--ctx-size"
      - "32768"
      # overall generation limit
      - "--n-predict"
      - "4096"
      # only 2k tokens on resoning
      - "--reasoning-budget"
      - "2048"

      - "--reasoning-format"
      - "deepseek"
      # server will only handle 1 request per
      - "--parallel"
      - "1"
      # a different implementation to speed up inference and reduce memory usage
      - "--flash-attn"
      - "on"
      - "--api-key"
      - "${LLAMA_API_KEY}"


    volumes:
      # uncomment if ansible download
      - /srv/llama-models:/models:ro
      # - /srv/llama-models:/models

    ports:
      - "8080:8080"

    networks:
      - ai

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.3
    container_name: open-webui
    restart: unless-stopped

    ports:
      - "3000:8080"

    volumes:
      - open-webui-data:/app/backend/data

    depends_on:
      - llama-server

    networks:
      - ai

networks:
  ai:

# where open-webui stores it's data
volumes:
  open-webui-data:

