- name: Deploy personal web app
  hosts: personal_web_app
  become: true

  vars:
    app_dir: /opt/personal-web-app

  tasks:
    - name: Configure DNS
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 192.168.1.1
          nameserver 1.1.1.1
        owner: root
        group: root
        mode: "0644" # rw-r--r--: owner (root) can read/write, group and others read-only

    - name: Install Docker and Docker Compose
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: Enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_dir }}/site"
        state: directory
        mode: "0755" # rwxr-xr-x: owner can read/write/enter dir, group and others can read/enter

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: ../../personal-web-app/compose.yml
        dest: "{{ app_dir }}/compose.yml"
        mode: "0644"

    - name: Copy Docker env file
      ansible.builtin.copy:
        src: ../../personal-web-app/.env
        dest: "{{ app_dir }}/.env"
        mode: "0644"
    
    # build website
    - name: Build website
      ansible.builtin.command:
        cmd: npm run build
        chdir: "{{app_dir}}"
      environment:
        NODE_ENV: production

    - name: Copy website
      ansible.builtin.copy:
        src: ../../personal-web-app/site/
        dest: "{{ app_dir }}/site/"
        mode: "0644"

    - name: Start Docker Compose project
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: present
        pull: missing